# Generated by Django 4.2.7 on 2025-10-27 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes_count', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_shipments', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='production.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes_count', models.IntegerField()),
                ('units_per_box', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_entries', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='production.materialtype')),
            ],
        ),
    ]
