# Generated by Django 4.2.7 on 2025-10-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_materialtype_materialshipment_materialentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyproduction',
            unique_together=set(),
        ),
    ]
