# Generated by Django 4.2.7 on 2025-10-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_dailyproduction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialshipment',
            name='units_per_box',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='materialentry',
            name='units_per_box',
            field=models.IntegerField(default=1),
        ),
    ]
